/** Traducciones del panel de plataforma. Claves: texto en español tal cual. */

export const EN_PLATAFORMA: Record<string, string> = {
  "las coaches": "the coaches",
  "No se pudo cargar el panel": "Couldn't load the panel",
  "coach": "coach",
  "coaches": "coaches",
  "alumnas activas": "active clients",
  "Coaches": "Coaches",
  "Dar de alta": "Create account",
  "Todavía no hay ninguna coach dada de alta.": "No coach has been created yet.",
  "En pausa": "On hold",
  "Baja": "Deactivated",
  "Cortesía": "Courtesy",
  "Al corriente": "Up to date",
  "Por vencer": "About to expire",
  "Vencida": "Overdue",
  "Cancelada": "Cancelled",
  "Nunca entró": "Never signed in",
  "{n} días sin entrar": "{n} days without signing in",
  "Cobros": "Payments",
  "Editar": "Edit",
  "Alumnas": "Clients",
  "Por validar": "To validate",
  "Chequeos del mes": "Monthly check-ins",
  "Fotos": "Photos",
  "Plan": "Plan",
  "Está por llegar a su límite de alumnas. Súbelo antes de que un alta le falle.":
    "She's close to her client limit. Raise it before a new sign-up fails.",
  "No se pudo dar de alta.": "The account couldn't be created.",
  "Coach creada": "Coach created",
  "Listo": "Done",
  "Apúntala ahora: no se vuelve a mostrar": "Write it down now: it won't be shown again",
  "Es temporal y se le pide cambiarla al entrar. Después de cerrar esto solo queda su hash, así que ni tú ni nadie puede volver a leerla.":
    "It's temporary and she'll be asked to change it on sign-in. After closing this only its hash remains, so neither you nor anyone else can read it again.",
  "Nueva coach": "New coach",
  "Nombre de la persona": "Person's name",
  "Nombre de la marca": "Brand name",
  "Lo que ven sus alumnas en la app y en los correos. Vacío = se usa su nombre.":
    "What her clients see in the app and in emails. Empty = her name is used.",
  "Correo": "Email",
  "Es su usuario para entrar. Único en toda la plataforma.":
    "It's her username to sign in. Unique across the whole platform.",
  "Límite de alumnas": "Client limit",
  "Precio de su ciclo": "Her cycle price",
  "Lo que ella le cobra a sus alumnas.": "What she charges her clients.",
  "Nace en cortesía: cobrarle desde el primer día a quien todavía no ha subido una sola alumna genera una factura que nadie va a pagar. La suscripción se ajusta después.":
    "She starts on courtesy: charging someone who has yet to upload a single client from day one produces an invoice nobody will pay. The subscription gets adjusted later.",
  "Guardar": "Save",
  "Lo que ven sus alumnas.": "What her clients see.",
  "Tiene {n} activas.": "She has {n} active.",
  "Estado de la cuenta": "Account status",
  "Activa": "Active",
  "Poner una cuenta en baja": "Putting an account on leave",
  "no borra nada": "deletes nothing",
  "Sus alumnas y sus expedientes siguen ahí: eliminar datos personales es otro flujo, con sus propios plazos, y no puede dispararse desde un selector.":
    "Her clients and their records stay there: deleting personal data is a separate flow, with its own deadlines, and can't be triggered from a selector.",
  "Suscripción": "Subscription",
  "Precio": "Price",
  "Periodicidad": "Frequency",
  "Mensual": "Monthly",
  "Anual": "Annual",
  "Estado": "Status",
  "Pagado hasta": "Paid through",
  "No se pudo guardar.": "It couldn't be saved.",
  "No se pudo registrar el cobro.": "The payment couldn't be recorded.",
  "Pagada hasta el {fecha}": "Paid through {fecha}",
  "Sin periodo pagado registrado": "No paid period recorded",
  "Monto": "Amount",
  "Fecha": "Date",
  "Cubre hasta": "Covers through",
  "Mueve la suscripción a «al corriente».": "Moves the subscription to «up to date».",
  "Registrar cobro": "Record payment",
  "Solo se agrega. Para corregir un cobro mal capturado se registra otro en negativo: lo que se cobró es un hecho, y un historial que se puede reescribir no sirve para cuadrar cuentas.":
    "It only adds. To fix a badly captured payment another one is recorded as negative: what was charged is a fact, and a history that could be rewritten is useless for balancing accounts.",
  "hasta {fecha}": "through {fecha}",
  "Todavía no le has registrado ningún cobro.": "You haven't recorded any payment for her yet.",
  "la facturación": "the billing",
  "No se pudo cargar la facturación": "Couldn't load the billing",
  "Todavía no hay nada que facturar.": "There's nothing to bill yet.",
  "Suscripciones de coaches": "Coach subscriptions",
  "Cobrado este año": "Billed this year",
  "Esperado al mes": "Expected per month",
  "suma de suscripciones activas": "sum of active subscriptions",
  "Vencidas": "Overdue",
  "{n} en cortesía": "{n} on courtesy",
  "Cobrado por mes": "Billed per month",
  "Con un mes de cobros todavía no hay línea que dibujar.":
    "With only a month of payments there's still no line to draw.",
  "Por cobrar": "To collect",
  "Nadie debe nada. Es la única cifra de esta pantalla que conviene que sea cero.":
    "Nobody owes anything. It's the only figure on this screen that's good to be zero.",
  "venció el {fecha}": "expired on {fecha}",
  "sin periodo pagado": "no paid period",
  "el estado del sistema": "the system status",
  "No se pudo consultar el estado": "Couldn't check the status",
  "Sin datos.": "No data.",
  "Estado del sistema": "System status",
  "{n} avisos se rindieron": "{n} notices gave up",
  "Fallaron cinco veces y ya no se reintentan. Revisa la configuración de correo: alguien no recibió su clave temporal o su recibo y no se enteró.":
    "They failed five times and are no longer retried. Check the email configuration: someone didn't receive their temporary key or receipt and never found out.",
  "{n} fotografías pasaron su plazo": "{n} photos passed their deadline",
  "Deberían estar borradas. Comprueba que el trabajo de purga esté corriendo:":
    "They should be deleted. Check that the purging job is running:",
  "El plazo de conservación está prometido por escrito en el Aviso de Privacidad.":
    "The retention deadline is promised in writing in the Privacy Notice.",
  "Avisos en cola": "Notices in queue",
  "{n} agotados": "{n} exhausted",
  "ninguno agotado": "none exhausted",
  "Fotos por purgar": "Photos to purge",
  "al día": "up to date",
  "revisar el trabajo": "check the job",
  "Almacenamiento": "Storage",
  "Sesiones vivas": "Live sessions",
  "Coaches activas": "Active coaches",
  "entraron este mes": "signed in this month",
  "Coaches inactivas": "Inactive coaches",
  "30 días o más sin entrar": "30 days or more without signing in",
  "Dispositivos con push": "Devices with push",
  "Último aviso enviado": "Last notice sent",
  "nunca": "never",
  "Movimientos recientes": "Recent activity",
  "Qué se hizo y en qué cuenta. Sin el detalle ni el identificador de la entidad: este panel no puede reconstruir a qué alumna corresponde cada movimiento, y esa es justamente la línea que lo mantiene del lado correcto de la ley.":
    "What was done and in which account. Without the detail or the entity identifier: this panel can't reconstruct which client each action belongs to, and that's precisely the line that keeps it on the right side of the law.",
  "la auditoría": "the audit log",
  "Todavía no hay movimientos registrados.": "No movements are recorded yet.",
  "Crear": "Create",
};
