/** Traducciones de las pantallas de coach. Claves: texto en español tal cual. */

export const EN_COACH: Record<string, string> = {
  /* ---- Compartidas / navegación ---- */
  "Agenda": "Schedule",
  "Finanzas": "Finances",
  "Apariencia": "Appearance",
  "Cobros": "Payments",
  "Solicitudes": "Requests",

  /* ---- Días de la semana (Agenda y Calendario: cabeceras cortas) ---- */
  "lun": "Mon",
  "mar": "Tue",
  "mié": "Wed",
  "jue": "Thu",
  "vie": "Fri",
  "sáb": "Sat",
  "dom": "Sun",
  "L": "Mo",
  "M": "Tu",
  "X": "We",
  "J": "Th",
  "V": "Fr",
  "S": "Sa",
  "D": "Su",

  /* ---- Días completos (Horario) ---- */
  "Lunes": "Monday",
  "Martes": "Tuesday",
  "Miércoles": "Wednesday",
  "Jueves": "Thursday",
  "Viernes": "Friday",
  "Sábado": "Saturday",
  "Domingo": "Sunday",

  /* ---- Rótulos compartidos (constantes de tipos) ---- */
  "Videollamada": "Video call",
  "Presencial": "In person",
  "Teléfono": "Phone",
  "Frontal": "Front",
  "Perfil": "Profile",
  "Espalda": "Back",
  "Cintura": "Waist",
  "Abdomen": "Abdomen",
  "Cadera": "Hips",
  "Busto": "Bust",
  "Pecho": "Chest",
  "Brazo": "Arm",
  "Muslo": "Thigh",
  "Pantorrilla": "Calf",
  "Pérdida de grasa": "Fat loss",
  "Ganancia de masa": "Muscle gain",
  "Recomposición": "Body recomposition",
  "Principiante": "Beginner",
  "Intermedio": "Intermediate",
  "Avanzado": "Advanced",

  /* ---- Niveles de actividad (objetivo del plan) ---- */
  "Muy poco activa": "Very little active",
  "Poco activa": "Little active",
  "Activa": "Active",
  "Muy activa": "Very active",
  "Intensa": "Intense",
  "Muy intensa": "Very intense",
  "Atleta": "Athlete",
  "Atleta de élite": "Elite athlete",

  /* ---- Finanzas: categorías ---- */
  "Ciclo mensual": "Monthly cycle",
  "Consulta suelta": "Single consult",
  "Otro ingreso": "Other income",
  "Plataforma": "Platform",
  "Equipo": "Equipment",
  "Local": "Venue",
  "Formación": "Training",
  "Publicidad": "Advertising",
  "Impuestos": "Taxes",
  "Otro gasto": "Other expense",

  /* ---- Motivos de cobro (CalendarioDeCobros) ---- */
  "Mensualidad del plan": "Plan membership",
  "Inscripción": "Enrollment",
  "Consulta": "Consult",
  "Material": "Material",
  "Otro concepto": "Another concept",

  /* ---- Presentacion: tipos de pregunta ---- */
  "Texto corto": "Short text",
  "Texto largo": "Long text",
  "Número": "Number",
  "Opción de una lista": "Choice from a list",
  "Sí o no": "Yes or no",

  /* ---- Presentacion: núcleo del cuestionario ---- */
  "Lesiones o cirugías": "Injuries or surgeries",
  "Condiciones médicas": "Medical conditions",
  "Medicación": "Medication",
  "Alergias y restricciones": "Allergies and restrictions",
  "Consentimientos de datos y fotografías": "Data and photo consent",

  /* ---- Solicitudes: pasos y estados de pago ---- */
  "sin confirmar su correo": "unconfirmed email",
  "contestando el cuestionario": "answering the questionnaire",
  "eligiendo su consulta": "choosing their consult",
  "pagando su inscripción": "paying their enrollment",
  "lista para que decidas": "ready for your decision",
  "decidida": "decided",
  "sin comprobante": "no receipt",
  "comprobante por revisar": "receipt under review",
  "pagada": "paid",

  /* =========================================================== Agenda === */
  "tu agenda": "your schedule",
  "consulta agendada": "consult scheduled",
  "consultas agendadas": "consults scheduled",
  "Vista del calendario": "Calendar view",
  "Nueva cita": "New appointment",
  "Semana": "Week",
  "Mes": "Month",
  "Hoy": "Today",
  "Sin título": "No title",
  "Editar cita": "Edit appointment",
  "Cancelar cita": "Cancel appointment",
  "Cita cancelada": "Appointment cancelled",
  "Cancelar": "Cancel",
  "Cancelar y avisar": "Cancel and notify",
  "Guardar": "Save",
  "Guardando…": "Saving…",
  "Empieza": "Starts",
  "Termina": "Ends",
  "a": "to",
  "Título": "Title",
  "Qué quieres cubrir en esta cita": "What you want to cover in this appointment",
  "Ponle un título: es lo que ve la paciente en su recordatorio.": "Give it a title: it's what the client sees in their reminder.",
  "Su consulta": "Their consult",
  "Su consulta: {fecha} a las {hora}": "Their consult: {fecha} at {hora}",
  "Consulta de seguimiento": "Follow-up consult",
  "Consulta con paciente": "Consult with client",
  "Bloque de trabajo": "Work block",
  "Modalidad": "Mode",
  "Día": "Day",
  "El bloque se libera y la hora vuelve a quedar disponible.": "The block is freed and the slot becomes available again.",
  "Notas": "Notes",
  "Nota (opcional)": "Note (optional)",
  "Motivo": "Reason",
  "«{nombre}» recibirá un aviso con el motivo tal como lo escribas.": "«{nombre}» will get a notification with the reason exactly as you write it.",
  "Ya tienes algo a esa hora": "You already have something at that time",
  "«{titulo}», de {inicio} a {fin}. Mueve una de las dos.": "«{titulo}», from {inicio} to {fin}. Move one of the two.",
  "La hora de fin tiene que ser posterior a la de inicio.": "The end time must be later than the start time.",
  "No se pudo guardar": "Couldn't save",
  "No se pudo guardar.": "Couldn't save.",
  "No se pudo cancelar.": "Couldn't cancel.",
  "Agendar": "Schedule",
  "Agendar el {dia} a las {hora}:00": "Schedule on {dia} at {hora}:00",
  "Toca un hueco para agendar ahí.": "Tap a slot to schedule there.",
  "Se me empalmó una urgencia, te reagendo el jueves.": "An urgent thing came up, I'll reschedule you for Thursday.",

  /* ======================================================== Validacion === */
  "Validar chequeo": "Review check-in",
  "Chequeo del {fecha}": "Check-in from {fecha}",
  "En revisión": "Under review",
  "Validado": "Validated",
  "Borrador": "Draft",
  "Rechazado": "Rejected",
  "Descartado": "Discarded",
  "Comparar contra": "Compare against",
  "Anterior": "Previous",
  "Este chequeo": "This check-in",
  "Ángulo": "Angle",
  "Ángulos": "Angles",
  "sin chequeo anterior": "no previous check-in",
  "Toma {angulo} del {fecha}": "{angulo} shot from {fecha}",
  "Medidas y peso": "Measurements and weight",
  "Peso": "Weight",
  "Estimación de grasa": "Fat estimate",
  "Obligatorio": "Required",
  "% de grasa corporal": "% body fat",
  "Masa grasa": "Fat mass",
  "Estimación de porcentaje de grasa": "Body fat percentage estimate",
  "Entre 3 % y 70 %.": "Between 3% and 70%.",
  "Revisión automática": "Automatic review",
  "Confirmó varianza": "Variance confirmed",
  "Alerta de outlier: {cambio} % de cambio": "Outlier alert: {cambio}% change",
  "Sobrescribes una alerta de outlier": "You're overriding an outlier alert",
  "Bajo umbral": "Below threshold",
  "Dentro de umbral": "Within threshold",
  "El sistema no juzga postura ni vestimenta. Eso lo ves tú.": "The system doesn't judge posture or clothing. That's for you to see.",
  "Postura": "Posture",
  "Vestimenta": "Clothing",
  "Entorno": "Environment",
  "Brazos relajados, abdomen neutro, sin poses": "Arms relaxed, neutral abdomen, no posing",
  "Short y top de color liso, según protocolo": "Plain-color shorts and top, per protocol",
  "Mismo lugar y misma luz que el chequeo anterior": "Same place and same light as the previous check-in",
  "Lo que revisas tú": "What you review",
  "Postura, vestimenta y entorno son lo que el sistema no puede juzgar. Puedes validar igual, pero conviene revisarlas.": "Posture, clothing and environment are what the system can't judge. You can still validate, but it's worth checking them.",
  "No marcaste toda la revisión manual": "You didn't complete the whole manual review",
  "Referencia visual": "Visual reference",
  "Ver tabla de referencia visual": "View the visual reference table",
  "Cuerpos de mujer y de hombre agrupados por porcentaje de grasa, del 1 % al 50 %.": "Female and male bodies grouped by body fat percentage, from 1% to 50%.",
  "Clasificación por índice de masa corporal": "Classification by body mass index",
  "IMC": "BMI",
  "Justificación técnica": "Technical justification",
  "Por qué consideras que el cambio es real": "Why you consider the change real",
  "La justificación es obligatoria y queda en el expediente.": "The justification is required and stays in the record.",
  "Feedback para la alumna": "Feedback for the client",
  "Es lo primero que va a leer. Concreto y sin juicio.": "It's the first thing they'll read. Specific and without judgment.",
  "En la foto de perfil metiste el abdomen. Repítela relajada.": "The profile photo shows your abdomen tucked in. Retake it relaxed.",
  "Qué debe corregir": "What to correct",
  "Corrígelo en el pago que lo originó": "Fix it in the payment that caused it",
  "Validar y enviar feedback": "Validate and send feedback",
  "Descartar": "Discard",
  "Descartar y avisarle": "Discard and notify them",
  "Validar": "Validate",
  "Rechazar con causa": "Reject with a reason",
  "Regresa a borrador para que vuelva a capturar. El motivo es obligatorio y ella lo ve tal cual: escríbelo como se lo dirías de frente.": "It goes back to draft so they can capture it again. The reason is required and they see it verbatim: write it as you'd tell them to their face.",
  "Se rechazó con causa. La alumna tiene que volver a capturarlo.": "It was rejected with a reason. The client has to capture it again.",
  "Este chequeo ya está validado": "This check-in is already validated",
  "Este chequeo ya se resolvió": "This check-in was already resolved",
  "Este chequeo no trae peso, así que no hay con qué calcular.": "This check-in has no weight, so there's nothing to calculate with.",
  "Perdió más de 1 kg de masa magra": "Lost more than 1 kg of lean mass",
  "Con este déficit no debería. Revisa proteína y adherencia antes de bajar más las calorías.": "It shouldn't happen with this deficit. Check protein and adherence before cutting calories further.",
  "No se pudo completar.": "Couldn't complete.",
  "No se pudo subir la foto.": "Couldn't upload the photo.",
  "No se pudo guardar el horario.": "Couldn't save the schedule.",

  /* ========================================================= Finanzas === */
  "Ingresos": "Income",
  "Gastos": "Expenses",
  "Utilidad": "Profit",
  "Mes a mes": "Month by month",
  "Últimos {meses} meses": "Last {meses} month(s)",
  "3 meses": "3 months",
  "6 meses": "6 months",
  "12 meses": "12 months",
  "24 meses": "24 months",
  "Proyección: {monto} al mes": "Projection: {monto} per month",
  "Es lo que entraría si tus {activas} alumnas activas renovaran. **Es una proyección, no un dato**: no la cuentes como ingreso hasta que esté cobrada.": "It's what would come in if your {activas} active clients renewed. **It's a projection, not a figure**: don't count it as income until it's collected.",
  "{activas} activas": "{activas} active",
  "Mes anterior": "Previous month",
  "Mes siguiente": "Next month",
  "Mes pasado: {valor}": "Last month: {valor}",
  "Ingreso": "Income",
  "Gasto": "Expense",
  "Movimientos": "Movements",
  "Movimiento": "Movement",
  "Nuevo movimiento": "New movement",
  "Editar movimiento": "Edit movement",
  "Sin movimientos en el periodo.": "No movements in this period.",
  "Todavía no hay movimientos en este periodo.": "No movements yet in this period.",
  "El periodo cierra en pérdida": "The period closes at a loss",
  "Gastaste {monto} más de lo que ingresaste.": "You spent {monto} more than you brought in.",
  "Historial de ingresos": "Income history",
  "Historial de gastos": "Expense history",
  "Categoría": "Category",
  "Fecha": "Date",
  "Concepto": "Concept",
  "De un pago": "From a payment",
  "Por paciente": "Per client",
  "Tipo": "Type",
  "Monto": "Amount",
  "Nota de la alumna": "Client's note",
  "Valor": "Value",
  "Orden": "Order",
  "Rótulo": "Label",
  "Paciente": "Client",
  "Estado": "Status",
  "Ingreso de «{nombre}». Para ligarlo a otra alumna, cancélalo y regístralo de nuevo.": "Income from «{nombre}». To link it to another client, cancel it and register it again.",
  "Importe tomado de {origen}: «{nombre}». Cámbialo si esta vez es distinto.": "Amount taken from {origen}: «{nombre}». Change it if it's different this time.",
  "¿De quién es el ingreso?": "Whose income is it?",
  "De aquí sale el precio de su ciclo.": "This is what their cycle is priced from.",
  "De aquí sale cuánto se le cobra. Los planes se crean en tus ajustes.": "This is what they're billed from. Plans are created in your settings.",
  "Escribe un concepto: sin él el movimiento no se entiende dentro de tres meses.": "Write a concept: without it the movement won't make sense in three months.",
  "Concepto (opcional)": "Concept (optional)",
  "Deja una línea en blanco para separar párrafos.": "Leave a blank line to separate paragraphs.",
  "Buscando…": "Searching…",
  "Escribe un nombre…": "Type a name…",
  "Nadie con cobros pendientes. Puedes registrarlo sin alumna.": "No one with outstanding balances. You can register it without a client.",
  "El monto tiene que ser mayor que cero.": "The amount must be greater than zero.",
  "No captures datos de salud aquí": "Don't capture health data here",
  "margen {margen}": "{margen} margin",
  "Se registra una sola vez.": "It's registered only once.",
  "Elige una…": "Choose one…",
  "Elige uno…": "Choose one…",
  "Suscripción de MyFittPlan · agosto": "MyFittPlan subscription · August",

  /* ======================================================= FormAlumna === */
  "Alta de alumna": "New client",
  "Editar alumna": "Edit client",
  "Nueva alumna": "New client",
  "Andrea Sáenz": "Andrea Sáenz",
  "Nombre completo": "Full name",
  "Falta el nombre.": "Name is missing.",
  "Ese correo no parece válido.": "That email doesn't look valid.",
  "Correo": "Email",
  "Fecha de nacimiento": "Date of birth",
  "Falta la fecha de nacimiento. El servicio es solo para mayores de 18 años.": "Date of birth is missing. The service is only for people 18 and over.",
  "Solo mayores de 18 años.": "Only people 18 and over.",
  "Estatura": "Height",
  "Falta su estatura en la ficha: sin ella no sale el IMC.": "Height is missing from the record: without it the BMI can't be shown.",
  "Nivel de experiencia": "Experience level",
  "Principiante, Intermedia, Avanzada": "Beginner, Intermediate, Advanced",
  "Báscula": "Scale",
  "Lugar de fotos": "Photo spot",
  "Grasa objetivo": "Target body fat",
  "{edad} años · {correo}": "{edad}y · {correo}",
  "Videollamada · audio de WhatsApp · la conozco en persona": "Video call · WhatsApp audio · I know them in person",
  "¿Cómo verificaste su identidad?": "How did you verify their identity?",
  "WhatsApp": "WhatsApp",
  "Recuperación de acceso": "Access recovery",
  "Generar clave": "Generate a key",
  "Vence en 24 horas. Al entrar se le pedirá cambiarla.": "Expires in 24 hours. They'll be asked to change it on sign-in.",
  "Vence en 24 horas. Al entrar se le pedirá cambiarla, y después completará su cuestionario y sus consentimientos ella misma.": "Expires in 24 hours. On sign-in they'll be asked to change it, then complete their questionnaire and consents themselves.",
  "Solo le sirve para entrar una vez": "It only works for a single sign-in",
  "Le mandamos la invitación a «{correo}» con esta contraseña. Es la misma para todas: díctasela sin problema.": "We send the invitation to «{correo}» with this password. It's the same for everyone: feel free to dictate it.",
  "En esta versión no hay recuperación automática por correo. Verifica que es ella antes de generar la clave.": "In this version there's no automatic recovery by email. Verify it's her before generating the key.",
  "Queda registrado. Sin esto, entregar una clave por WhatsApp es indistinguible de dársela a quien se hizo pasar por ella.": "It's recorded. Without this, handing out a key over WhatsApp is indistinguishable from giving it to someone impersonating them.",
  "Alumna dada de alta": "Client enrolled",
  "Su historial clínico y sus consentimientos los llena ella al entrar. La ley exige que el consentimiento para datos sensibles sea personal, así que capturarlo tú lo invalidaría.": "Their clinical history and consents are filled by them on sign-in. The law requires consent for sensitive data to be personal, so you capturing it would invalidate it.",
  "Al entrar, lo primero que ve es la pantalla para ponerse la suya. Hasta que lo haga, el sistema no le abre nada más.": "On sign-in, the first screen they see is for their check-in. Until they do it, the system won't open anything else.",
  "Aceptar confirma su consulta, abre su ciclo y le deja el chequeo disponible. Ninguna cuenta contra tu límite hasta que la aceptes.": "Accepting confirms their consult, opens their cycle and makes the check-in available. Nothing counts against your limit until you accept.",
  "Sin plan por ahora": "No plan for now",
  "Sin plan asignado": "No plan assigned",
  "Plan": "Plan",
  "Plan que pide": "Plan they request",
  "Plan que le confirmas": "Plan you confirm",
  "Ella pidió {plan}. De aquí sale el precio de su ciclo.": "They requested {plan}. This is what their cycle is priced from.",
  "Con esto la calculadora proyecta cuánto le falta. Solo lo ves tú.": "With this the calculator projects how much is left. Only you see it.",
  "Su plan se calculó con estos números. Cambiarlos ahora dejaría el plan publicado diciendo otra cosa.": "Their plan was calculated with these numbers. Changing them now would leave the published plan saying something else.",
  "no cabe ninguna consulta": "no consult fits",
  "Sin este dato el constructor no puede calcular calorías ni macros del ciclo siguiente.": "Without this the builder can't calculate calories or macros for the next cycle.",
  "Quitar": "Remove",
  "Quitar dato": "Remove field",
  "No se pueden quitar: tu constructor los usa para avisarte de una lesión al elegir ejercicios, y el consentimiento de datos de salud lo exige la ley.": "They can't be removed: your builder uses them to warn you about an injury when choosing exercises, and health-data consent requires it by law.",
  "Se le enviará también por correo": "It will also be sent by email",
  "No se pudo generar.": "Couldn't generate.",

  /* ====================================================== Presentacion === */
  "Tu presentación": "Your presentation",
  "Tu ficha": "Your profile",
  "Tu foto": "Your photo",
  "Subir foto": "Upload photo",
  "Cambiar foto": "Change photo",
  "Sin foto": "No photo",
  "Encuadre sin rostro. Cada apertura queda en la bitácora de accesos.": "Framing without the face. Every opening is logged in the access log.",
  "Guardar presentación": "Save presentation",
  "Presentación actualizada.": "Presentation updated.",
  "Hola, soy Mariana": "Hi, I'm Mariana",
  "Lo primero que lee.": "The first thing they read.",
  "Es lo primero que ve una alumna nueva, antes del cuestionario. Escríbela como se la contarías en persona.": "It's the first thing a new client sees, before the questionnaire. Write it as you'd tell them in person.",
  "Llevo doce años acompañando a mujeres…": "I've been supporting women for twelve years…",
  "Es una guía de apoyo, no una medición: toma el rango que más se parezca.": "It's a support guide, not a measurement: take the range that looks closest.",
  "Mientras esto esté vacío, tus alumnas no pueden reservar consulta contigo.": "While this is empty, your clients can't book a consult with you.",
  "Mostrarla a las alumnas nuevas": "Show it to new clients",
  "Apagada, tus alumnas nuevas van directo al cuestionario.": "When off, new clients go straight to the questionnaire.",
  "Se muestra": "Shown",
  "Apagada": "Off",
  "Tu cara, no tu logo. Se recorta al centro en un cuadrado.": "Your face, not your logo. It's center-cropped to a square.",
  "Encabezado": "Header",
  "Tu condición necesita seguimiento médico que yo no doy.": "Your condition needs medical follow-up that I don't provide.",
  "Preguntas": "Questions",
  "Tus preguntas": "Your questions",
  "Tú nombras los campos: certificaciones, años de experiencia, enfoque…": "You name the fields: certifications, years of experience, focus…",
  "Certificaciones": "Certifications",
  "ISAK nivel 1, NSCA-CPT": "ISAK level 1, NSCA-CPT",
  "Sepáralas con comas.": "Separate them with commas.",
  "Opciones": "Options",
  "Obligatoria": "Required",
  "Siempre se pregunta": "Always asked",
  "Lo contesta cada alumna nueva justo después de leer tu presentación.": "Every new client answers it right after reading your presentation.",
  "Cuestionario inicial": "Initial questionnaire",
  "Todavía no agregas ninguna. El núcleo se pregunta de todos modos.": "You haven't added any yet. The core is still asked regardless.",
  "Editar": "Edit",
  "Borrar": "Delete",
  "Eliminar": "Delete",
  "Ocultar lo que contestó": "Hide their answers",
  "Ver lo que contestó": "See their answers",
  "No contestó ninguna de tus preguntas.": "They didn't answer any of your questions.",
  "Todavía no reserva consulta": "Hasn't booked a consult yet",
  "Todavía no sube comprobante: puedes aceptarla igual y queda el adeudo": "Haven't uploaded a receipt yet: you can still accept and the balance stays",
  "Nadie ha empezado su registro todavía. Comparte tu liga desde la pantalla de tus alumnas.": "No one has started registering yet. Share your link from your clients screen.",
  "Llegaron por tu liga": "Came in through your link",
  "Todavía en su recorrido": "Still on their journey",
  "Te toca decidir": "Your decision",
  "Aceptar": "Accept",
  "Al aceptarla entra a tu cartera y empieza a contar contra tu límite.": "Once you accept they join your roster and start counting against your limit.",
  "Ahí le llega su invitación.": "That's where their invitation arrives.",

  /* ================================================= CalendarioDeCobros === */
  "Programar cobro": "Schedule payment",
  "Programar": "Schedule",
  "debe {monto}": "owes {monto}",
  "Toca un día para programar un cobro. Uno vencido le pausa el plan. El cuadrito marca una consulta agendada.": "Tap a day to schedule a payment. An overdue one pauses their plan. The little square marks a scheduled consult.",
  "Consultas agendadas": "Scheduled consults",
  "Su chequeo se abre tres días antes de cada una y se cierra tres después.": "Their check-in opens three days before each one and closes three days after.",
  "Sin consultas agendadas. Hasta que le agendes una desde tu agenda, no puede capturar su chequeo.": "No scheduled consults. Until you schedule one from your schedule, they can't capture their check-in.",
  "pagado": "paid",
  "vencido": "overdue",
  "Ya programado ese día": "Already scheduled that day",
  "De tu lista de precios": "From your price list",
  "su plan": "their plan",
  "tu lista de precios": "your price list",
  "Si lo dejas vacío se usa el motivo.": "If you leave it empty, the reason is used.",
  "Mensualidad de septiembre": "September membership",
  "La alumna lo ve en sus próximas fechas. Si llega el día y no ha pagado, su plan se pausa hasta que registres el ingreso.": "The client sees it in their upcoming dates. If the day comes and they haven't paid, their plan pauses until you record the income.",
  "No se pudo programar el cobro.": "Couldn't schedule the payment.",

  /* ====================================================== Calendario === */
  "Cerrar": "Close",
  "más": "more",

  /* ========================================================= Horario === */
  "Horario de consultas": "Consultation hours",
  "Cuándo pueden reservarte": "When they can book you",
  "Las horas van en tu hora local ({zona}). Cada alumna las ve convertidas a la suya.": "The times are in your local time ({zona}). Each client sees them converted to theirs.",
  "Todavía no publicas horarios": "You haven't published a schedule yet",
  "Copiar a lunes–viernes": "Copy to Monday–Friday",
  "Tramo": "Block",
  "No atiendes este día.": "You're not available this day.",
  "{dia}: desde": "{dia}: from",
  "{dia}: hasta": "{dia}: until",
  "Quitar tramo de {dia}": "Remove {dia} block",
  "1 consulta": "1 consult",
  "{n} consultas": "{n} consults",
  "Cómo se trocea": "How it's split",
  "Cada consulta dura lo que digas aquí, y entre una y otra queda el respiro que elijas.": "Each consult lasts what you set here, and between each one there's the breather you choose.",
  "Dura cada consulta": "Each consult lasts",
  "Respiro entre consultas": "Breather between consults",
  "Con cuánta antelación": "How much notice",
  "Nadie puede reservarte con menos aviso que esto.": "No one can book you with less notice than this.",
  "Hasta cuándo se ve": "How far ahead it's visible",
  "Más allá de esto no aparece nada libre.": "Beyond this, nothing free appears.",
  "Con este horario no ofreces ninguna consulta": "With this schedule you offer no consults",
  "Ofreces {n} consultas por semana": "You offer {n} consults per week",
  "Guardar horario": "Save schedule",
  "Horario guardado.": "Schedule saved.",
  "No puedes tener más de {max} tramos.": "You can't have more than {max} blocks.",
  "{dia}: la hora de fin tiene que ir después de la de inicio.": "{dia}: the end time must come after the start time.",
  "{dia}: tienes dos tramos encimados.": "{dia}: you have two overlapping blocks.",

  /* ======================================================== Apariencia === */
  "Cómo se ve tu plataforma": "How your platform looks",
  "Tu marca": "Your brand",
  "Tus alumnas ven tu logo y tu color dentro de la plataforma.": "Your clients see your logo and your color inside the platform.",
  "Tu logo": "Your logo",
  "Cambiar logo": "Change logo",
  "Subir logo": "Upload logo",
  "Se recorta al centro en un cuadrado. Sin logo se usan tus iniciales.": "It's center-cropped to a square. Without a logo your initials are used.",
  "Tu nombre": "Your name",
  "Nombre de tu marca": "Name of your brand",
  "Es lo que ven tus alumnas. Puede no ser tu nombre.": "It's what your clients see. It doesn't have to be your name.",
  "Color de acento": "Accent color",
  "Filetes, bordes, iconos y estados activos.": "Outlines, borders, icons and active states.",
  "Color secundario": "Secondary color",
  "Acompaña al acento. Sirve para separar dos bloques hermanos.": "Pairs with the accent. It helps separate two sibling blocks.",
  "{etiqueta} en hexadecimal": "{etiqueta} in hexadecimal",
  "Acento": "Accent",
  "Secundario": "Secondary",
  "en filete": "in outline",
  "en texto": "in text",
  "Fondo teñido": "Tinted background",
  "Cómo se ven en cada tema": "How they look in each theme",
  "Claro": "Light",
  "Oscuro": "Dark",
  "Elige el color que quieras: el sistema lo aclara u oscurece lo justo para que se lea en cada tema, sin cambiarle el tono.": "Pick whatever color you want: the system lightens or darkens it just enough to read in each theme, without changing its hue.",
  "Guardar marca": "Save brand",
  "Marca actualizada.": "Brand updated.",
  "Claro y oscuro": "Light and dark",
  "Solo cambia cómo lo ves tú. Cada alumna elige el suyo.": "It only changes how you see it. Each client picks their own.",
  "No se pudo guardar la marca.": "Couldn't save the brand.",
  "No se pudo subir el logo.": "Couldn't upload the logo.",

  /* ===================================================== Comprobantes === */
  "Comprobantes por revisar": "Receipts to review",
  "Confirma cada uno contra tu estado de cuenta. Al validarlo se registra el ingreso y el cobro deja de contar como adeudo.": "Check each one against your bank statement. Validating it records the income and the payment stops counting as a balance.",
  "leyó": "read",
  "Comprobante": "Receipt",
  "Comprobante de {alumna}": "Receipt of {alumna}",
  "Comprobante de {nombre}": "Receipt of {nombre}",
  "Revisar": "Review",
  "Volver": "Back",
  "Rechazar y avisar": "Reject and notify",
  "Rechazar": "Reject",
  "Validar pago": "Validate payment",
  "El importe leído no coincide": "The amount read doesn't match",
  "Esperabas {a} y la captura dice {b}. Compruébalo contra tu estado de cuenta.": "You expected {a} and the capture reads {b}. Check it against your bank statement.",
  "Esperabas {esperado} y la captura dice {leido}. Compruébalo contra tu estado de cuenta antes de validar.": "You expected {esperado} and the capture reads {leido}. Check it against your bank statement before validating.",
  "Esperado": "Expected",
  "Leído": "Read",
  "Fecha leída": "Date read",
  "Banco": "Bank",
  "Referencia": "Reference",
  "Confianza": "Confidence",
  "¿Por qué lo rechazas?": "Why are you rejecting it?",
  "La captura está cortada y no se ve la referencia.": "The capture is cut off and the reference isn't visible.",
  "Validar registra el ingreso, salda el cobro y le avisa. Rechazar le devuelve el motivo tal como lo escribas.": "Validating records the income, settles the payment and lets them know. Rejecting returns the reason exactly as you write it.",
  "El OCR solo sugiere: lo que vale es tu estado de cuenta.": "The OCR only suggests: what counts is your bank statement.",
  "Tu navegador no puede enseñar el PDF aquí. Ábrelo en otra pestaña.": "Your browser can't show the PDF here. Open it in another tab.",
  "No se pudo cargar la imagen del comprobante.": "Couldn't load the receipt image.",
  "Abrir en otra pestaña": "Open in another tab",

  /* ============================================================= Hoja === */
  "Calculando…": "Calculating…",
  "No se pudo abrir la calculadora.": "Couldn't open the calculator.",
  "Calculadora": "Calculator",
  "Todavía no hay con qué calcular": "There's nothing to calculate with yet",
  "Ver fórmulas": "Show formulas",
  "Ocultar fórmulas": "Hide formulas",
  "Ver tablas": "Show tables",
  "Ocultar tablas": "Hide tables",
  "capturados": "captured",
  "calculados": "calculated",

  /* ---- Resto de claves literales ---- */
  "{alumna} todavía no ha enviado ningún chequeo.": "{alumna} hasn't sent any check-in yet.",
  "{min} minutos": "{min} minutes",
  "Al aceptarla queda confirmada y se le avisa por correo.": "Once you accept, it's confirmed and they're notified by email.",
  "Al elegir uno se llenan el importe y el concepto. Puedes cambiarlos después.": "Choosing one fills in the amount and the concept. You can change them afterwards.",
  "Al registrarlo, ese cobro queda saldado y deja de contar como adeudo.": "Registering it settles that payment and it stops counting as a balance.",
  "Cambiar": "Change",
  "Comparativa visual": "Visual comparison",
  "Copiada": "Copied",
  "Copiar": "Copy",
  "Dar de alta": "Enroll",
  "Dar por bueno el comprobante y registrar el ingreso": "Approve the receipt and record the income",
  "Dato": "Field",
  "De {a} kg a {b} kg en un ciclo. Para validar tendrás que escribir por qué lo consideras real.": "From {a} kg to {b} kg in one cycle. To validate you'll have to write why you consider it real.",
  "el expediente": "the record",
  "Elige de quién es: toda cita va también al expediente de la paciente.": "Choose whose it is: every appointment also goes into the client's record.",
  "En pausa": "On pause",
  "Escríbelo para tu yo de dentro de tres meses.": "Write it for yourself three months from now.",
  "Esta alumna": "This client",
  "Estas fotos se purgan pronto": "These photos are purged soon",
  "Esto es contabilidad de gestión, para saber si tu negocio gana dinero. No sustituye tu contabilidad fiscal: pídele a tu contador lo que necesite.": "This is management accounting, to know whether your business makes money. It's not a substitute for your tax accounting: ask your accountant for what you need.",
  "Expediente": "Record",
  "Hora": "Time",
  "Lesiones declaradas": "Declared injuries",
  "Listo": "Done",
  "Lo lee ella tal cual en su correo, así que escríbelo para ella.": "They read it verbatim in their email, so write it for them.",
  "Más de 8 horas: revisa que la fecha de fin sea la correcta.": "More than 8 hours: check that the end date is correct.",
  "Masa magra": "Lean mass",
  "Medidas": "Measurements",
  "Mejor no": "Better not",
  "Muy corta. El mínimo son {min} minutos.": "Too short. The minimum is {min} minutes.",
  "Nitidez": "Sharpness",
  "No hay nada que validar": "Nothing to validate",
  "No hizo falta": "Wasn't needed",
  "No se pudieron cargar sus datos.": "Their data couldn't be loaded.",
  "No se pudo abrir el expediente": "Couldn't open the record",
  "No se pudo eliminar.": "Couldn't delete.",
  "pendiente": "pending",
  "pendientes": "pending",
  "Periodo": "Period",
  "Pierde el acceso hoy": "Loses access today",
  "Por qué": "Why",
  "Pregunta": "Question",
  "Qué le cobras": "What you charge them",
  "Qué ves, qué cambia y por qué": "What you see, what changes and why",
  "se borra en {dias} d": "is deleted in {dias} d",
  "Sí": "Yes",
  "Si no terminan, su registro se borra solo y no queda nada suyo. Se les avisa dos días antes.": "If they don't finish, their registration self-deletes and nothing of theirs is kept. They're warned two days before.",
  "Siguiente": "Next",
  "Sin datos": "No data",
  "Sin datos todavía.": "No data yet.",
  "sin plan": "no plan",
  "sin reservar": "unbooked",
  "Solicitud": "Request",
  "Su primera y su última de cada ángulo se quedan. A la alumna ya se le avisó, con enlace para descargar todo.": "Their first and last of each angle are kept. The client has already been notified, with a link to download everything.",
  "Su registro y todo lo que capturó se borran en 7 días. La consulta que había reservado queda libre para otra.": "Their registration and everything they captured are deleted in 7 days. The consult they'd booked becomes free for someone else.",
  "sus datos": "their data",
  "tu horario": "your schedule",
  "tus solicitudes": "your requests",
  "Un momento…": "One moment…",
  "Volver a intentar": "Try again",

  /* ---- Bancos y catálogos (BuscadorCatalogo) ---- */
  "Agregar": "Add",
  "Buscar": "Search",
  "Agregar alimento": "Add food",
  "Nuevo alimento": "New food",
  "Guardar alimento": "Save food",
  "No se pudo guardar el alimento.": "The food couldn't be saved.",
  "Busca en el catálogo": "Search the catalog",
  "Pechuga, garbanzos, requesón…": "Chicken breast, chickpeas, cottage cheese…",
  "Unidad": "Unit",
  "Gramos": "Grams",
  "Mililitros": "Milliliters",
  "gramos": "grams",
  "mililitros": "milliliters",
  "Los valores van por 100 {unidad}.": "Values are per 100 {unidad}.",
  "Calorías": "Calories",
  "Pollo, avena, tortilla…": "Chicken, oats, tortilla…",
  "Tuyo": "Yours",
  "El catálogo trae la base pública más tus alimentos propios. Si falta alguno, créalo aquí.":
    "The catalog brings the public base plus your own foods. If something's missing, create it here.",
  "Cantidad": "Amount",
  "Referencia del catálogo: {porcion} {unidad} = {kcal} kcal.":
    "Catalog reference: {porcion} {unidad} = {kcal} kcal.",
  "Carbos": "Carbs",
  "Escribe una cantidad mayor que cero.": "Enter an amount greater than zero.",
  "Elegir otro alimento": "Choose another food",
  "Agregar ejercicio": "Add exercise",
  "Nuevo ejercicio": "New exercise",
  "Guardar ejercicio": "Save exercise",
  "No se pudo guardar el ejercicio.": "The exercise couldn't be saved.",
  "Músculo que trabaja": "Muscle worked",
  "Press banca, remo, zancada…": "Bench press, row, lunge…",
  "Pecho, espalda, pierna…": "Chest, back, legs…",
  "Barra, mancuernas, máquina, peso corporal…": "Barbell, dumbbells, machine, bodyweight…",
  "Tipo de movimiento": "Movement pattern",
  "Empuje, jalón, sentadilla, bisagra…": "Push, pull, squat, hinge…",
  "Se guarda en tu banco con el sello «Tuyo» y queda para esta alumna y las que siguen.":
    "It's saved to your library with the “Yours” seal and stays available for this client and all the ones after.",
  "Sentadilla, remo, hip thrust…": "Squat, row, hip thrust…",
  "Con video": "With video",
  "El banco trae la base pública más tus ejercicios propios. Si falta alguno, créalo aquí.":
    "The library brings the public base plus your own exercises. If something's missing, create it here.",
  "Recuerda su historial": "Keep her history in mind",
  "Contraindicaciones de este ejercicio": "Contraindications for this exercise",
  "Series": "Sets",
  "Repeticiones": "Reps",
  "Carga": "Load",
  "45 kg": "45 kg",
  "Nota de ejecución (opcional)": "Execution note (optional)",
  "La alumna la ve debajo del ejercicio, en su plan y en el PDF.":
    "The client sees it below the exercise, in her plan and in the PDF.",
  "Profundidad hasta paralelo. Nada de valgo.": "Depth to parallel. No valgus.",
  "Elegir otro ejercicio": "Choose another exercise",

  /* ---- Editor del plan (EditorPlan) ---- */
  "Tiempos de comida": "Mealtimes",
  "Tiempo": "Time",
  "Tiempo {n}": "Time {n}",
  "Los macros salen del catálogo: tú eliges el alimento y la cantidad.":
    "Macros come from the catalog: you pick the food and the amount.",
  "Agrega alimentos y verás cómo se acerca al objetivo.":
    "Add foods and you'll see it approach the target.",
  "Cuadra con el objetivo.": "It matches the target.",
  "Faltan {faltan} kcal{exceso}.": "Missing {faltan} kcal{exceso}.",
  " — te pasaste por {extra}": " — you're over by {extra}",
  "{capturado} de {objetivo} kcal capturadas": "{capturado} of {objetivo} kcal logged",
  "Proteína {capturada} / {objetivo} g · Carbos {carbo} / {carboObjetivo} g · Grasa {grasa} / {grasaObjetivo} g":
    "Protein {capturada} / {objetivo} g · Carbs {carbo} / {carboObjetivo} g · Fat {grasa} / {grasaObjetivo} g",
  "Todavía no hay tiempos de comida. Agrega el primero.":
    "No mealtimes yet. Add the first one.",
  "Quitar tiempo": "Remove mealtime",
  "Sin alimentos todavía.": "No foods yet.",
  "Alimento": "Food",
  "Estructura de la semana": "Week structure",
  "{dias} días · {ejercicios} ejercicios": "{dias} days · {ejercicios} exercises",
  "Día {n}": "Day {n}",
  "Plantilla base": "Base template",
  "Aparece en el PDF de la alumna.": "Shows up in the client's PDF.",
  "Fuerza superior/inferior — 4 días": "Upper/lower strength — 4 days",
  "Cuidado con su historial": "Careful with her history",
  "Todavía no hay días. Agrega el primero.": "No days yet. Add the first one.",
  "Quitar día": "Remove day",
  "Sin ejercicios todavía.": "No exercises yet.",
  "Nota": "Note",
  "Ejercicio": "Exercise",

  /* ---- Constructor de planes (Constructor) ---- */
  "Abriendo el expediente…": "Opening the file…",
  "No se pudo abrir el plan": "The plan couldn't be opened",
  "Vuelve a intentarlo.": "Try again.",
  "Ciclo {n} · borrador": "Cycle {n} · draft",
  "Plan de {alumna}": "Plan for {alumna}",
  "PDF nutrición": "Nutrition PDF",
  "PDF rutina": "Routine PDF",
  "Guardar borrador": "Save draft",
  "Publicando…": "Publishing…",
  "Publicar": "Publish",
  "Borrador guardado.": "Draft saved.",
  "Plan publicado. La alumna ya lo ve.": "Plan published. The client can now see it.",
  "No se puede publicar todavía": "Can't be published yet",
  "El chequeo de {fecha} sigue sin validar.": "The check-in from {fecha} is still unreviewed.",
  "Todavía no hay ningún chequeo en este ciclo.": "There's no check-in in this cycle yet.",
  "Sin chequeo validado no se publica plan nuevo: es la guarda de continuidad del método.":
    "Without a validated check-in no new plan is published: it's the continuity guard of the method.",
  "Ir a validarlo": "Review it",
  "Secciones del expediente": "File sections",
  "Programa": "Program",
  "Composición corporal": "Body composition",
  "% de grasa": "% body fat",
  "Peso ideal (Broca)": "Ideal weight (Broca)",
  "Diferencia": "Difference",
  "Del chequeo del {fecha}. No se captura aquí.": "From the {fecha} check-in. It's not typed here.",
  "Sin chequeo en este ciclo todavía.": "No check-in in this cycle yet.",
  "Ver el chequeo": "View the check-in",
  "Falta el porcentaje de grasa": "Body fat percentage is missing",
  "Estímalo al validar el chequeo. Es la entrada que manda toda la cadena de cálculo.":
    "Estimate it when reviewing the check-in. It's the input that drives the whole calculation chain.",
  "Sin chequeo validado todavía.": "No validated check-in yet.",
  "Aún no hay composición que mostrar": "There's no body composition to show yet",
  "Aún no hay un chequeo validado del que salga el peso, las medidas y la composición":
    "There's no validated check-in yet to draw the real weight, measurements, and body composition from.",
  "Ir a validar el chequeo": "Go review the check-in",
  "Falta el primer chequeo validado": "The first validated check-in is missing",
  "Sin un chequeo validado no hay peso real con qué calcular, así que la calculadora queda vacía. Valida el primer chequeo de este ciclo y aquí aparecerán sus cifras.":
    "Without a validated check-in there's no real weight to work with, so the calculator stays empty. Validate the first check-in of this cycle and its figures will appear here.",
  "Mueve cualquier campo y todo se recalcula. Estos parámetros quedan guardados en el ciclo, para poder entender después por qué un mes funcionó y otro no.":
    "Move any field and everything recalculates. These parameters are saved in the cycle, so you can later understand why one month worked and another didn't.",
  "Nivel de actividad": "Activity level",
  "Ajuste calórico": "Caloric adjustment",
  "Negativo es déficit, positivo es superávit.": "Negative is a deficit, positive is a surplus.",
  "% Grasa objetivo": "% Target body fat",
  "Meta para proyectar la pérdida.": "Goal for projecting the loss.",
  "Reparto de macros — tiene que sumar 100 %":
    "Macro split — it has to add up to 100 %",
  "El reparto suma {suma} %": "The split adds up to {suma} %",
  "Tiene que sumar exactamente 100 % para poder calcular los gramos.":
    "It has to add up to exactly 100 % to calculate the grams.",
  "Proteína contra": "Protein based on",
  "Masa libre de grasa": "Fat-free mass",
  "Peso total": "Total weight",
  "Días de refeed": "Refeed days",
  "Ninguno": "None",
  "1 día por semana": "1 day per week",
  "2 días por semana": "2 days per week",
  "Déficit del refeed": "Refeed deficit",
  "Cero es mantenimiento, que es lo habitual.": "Zero is maintenance, the usual.",
  "Resultado": "Result",
  "TMB {tmb} kcal · mantenimiento {manto} kcal": "BMR {tmb} kcal · maintenance {manto} kcal",
  "Déficit": "Deficit",
  "Superávit": "Surplus",
  "Objetivo diario": "Daily target",
  "Ajuste diario": "Daily adjustment",
  "Recomendado −{min} a −{max}": "Recommended −{min} to −{max}",
  "Ajuste semanal": "Weekly adjustment",
  "Con {n} {dias} de refeed, el déficit real de la semana es {pct} %":
    "With {n} {dias} of refeed, the week's real deficit is {pct} %",
  "día": "day",
  "días": "days",
  "El día bajo va al {pct} %, pero lo que manda sobre el resultado es el promedio semanal.":
    "The low day goes to {pct} %, but what drives the result is the weekly average.",
  "Tipo de plan": "Plan type",
  "Nutrición": "Nutrition",
  "Entrenamiento": "Training",
  "Fotos de sus comidas": "Photos of her meals",
  "Cada foto se borra sola a las 36 horas de que la manda.":
    "Each photo deletes itself 36 hours after she sends it.",
  "No pedirle fotos": "Don't ask for photos",
  "Todos los días": "Every day",
  "Una vez por semana": "Once a week",
  "Cada quince días": "Every two weeks",
  "Una vez al mes": "Once a month",
  "Notas para la alumna": "Notes for the client",
  "Notas de ejecución": "Execution notes",
  "Restricciones": "Restrictions",
  "Sin restricciones registradas en su historial.": "No restrictions on file in her history.",
  "Su cuestionario": "Her questionnaire",
  "Sus comidas": "Her meals",
  "Se borran solas a las 36 horas de que las manda.":
    "They delete themselves 36 hours after she sends them.",
  "Ahora mismo no tiene ninguna vigente.": "She doesn't have any active right now.",
  "Comida": "Meal",
  "Sin titulo": "Untitled",
  "Buena porcion.": "Good portion.",
  "Comentario": "Comment",
  "Comentar": "Comment",
};
