/** Traducciones de las pantallas de la alumna. Claves: texto en español tal cual. */

export const EN_ALUMNA: Record<string, string> = {
  "tu coach": "your coach",
  "Regresar": "Back",
  "Avisos": "Notices",
  "Lo que te manda {marca}": "What {marca} sends you",
  "Del más reciente al más antiguo. No se guardan: una vez leídos desaparecen.": "From newest to oldest. They aren't kept: once read, they disappear.",
  "tus avisos": "your notices",
  "Todavía no tienes avisos.": "You don't have any notices yet.",
  "Un momento…": "One moment…",
  "No se pudo abrir el cuestionario": "The questionnaire couldn't be opened",
  "Vuelve a intentarlo en un momento.": "Try again in a moment.",
  "Bienvenida": "Welcome",
  "Empezar": "Get started",
  "No se pudo guardar.": "It couldn't be saved.",
  "Antes de empezar": "Before you begin",
  "Cuéntale a tu coach": "Tell your coach about yourself",
  "De esto depende que tu plan sea seguro. Si algo cambia después, lo puedes editar desde tu cuenta.": "Your plan's safety depends on this. If something changes later, you can edit it from your account.",
  "Tu salud": "Your health",
  "Lesiones o cirugías": "Injuries or surgeries",
  "Condiciones médicas": "Medical conditions",
  "Medicación": "Medication",
  "Alergias y restricciones": "Allergies and restrictions",
  "Esguince de tobillo en 2023, ya recuperado.": "Ankle sprain in 2023, already healed.",
  "Hipotiroidismo controlado.": "Controlled hypothyroidism.",
  "Levotiroxina 50 mcg diaria.": "Levothyroxine 50 mcg daily.",
  "Intolerancia a la lactosa. No como mariscos.": "Lactose intolerance. I don't eat seafood.",
  "Si no aplica, déjalo vacío. Es mejor eso que escribir «nada».": "If it doesn't apply, leave it blank. Better that than writing \"nothing\".",
  "Lo que tu coach quiere saber": "What your coach wants to know",
  "Qué plan quieres": "Which plan you want",
  "Es lo que le pides a tu coach. Ella lo confirma al aceptarte, y de ahí sale tu primer ciclo.": "It's what you ask your coach for. She confirms it when she accepts you, and your first cycle comes out of that.",
  "días": "days",
  "Acepto {rotulo}": "I accept {rotulo}",
  "Términos y Condiciones": "Terms and Conditions",
  "Aviso de Privacidad": "Privacy Notice",
  "Tratamiento de mis datos de salud": "Processing of my health data",
  "Protocolo fotográfico": "Photo protocol",
  "Leerlo antes de aceptar": "Read it before accepting",
  "Guardando…": "Saving…",
  "Listo": "Done",
  "Falta contestar: {texto}": "Missing an answer: {texto}",
  "Falta aceptar los permisos para poder continuar.": "You still need to accept the permissions to continue.",
  "Elige una": "Choose one",
  "Sí": "Yes",
  "No": "No",
  "Permisos": "Permissions",
  "Guardamos la fecha y el texto exacto que aceptas. Puedes revocarlos cuando quieras desde tu cuenta.": "We keep the date and the exact text you accept. You can revoke them whenever you want from your account.",
  "Estado": "Status",
  "Peso": "Weight",
  "Medidas": "Measurements",
  "Fotos": "Photos",
  "Envío": "Submit",
  "Escribe solo el número.": "Write only the number.",
  "Muy poco. {rotulo} va de {min} a {max} cm.": "Too low. {rotulo} goes from {min} to {max} cm.",
  "Muy alto. {rotulo} va de {min} a {max} cm.": "Too high. {rotulo} goes from {min} to {max} cm.",
  "Estoy en ayunas": "I'm fasting",
  "Nada de comida ni bebida desde anoche, tampoco agua.": "No food or drink since last night, not even water.",
  "Acabo de despertar": "I just woke up",
  "Es lo primero que hago hoy.": "It's the first thing I do today.",
  "Ya fui al baño": "I already used the bathroom",
  "Evacué antes de pesarme.": "I went before weighing myself.",
  "No he entrenado": "I haven't worked out",
  "Ni entrenamiento ni cardio hoy.": "No training or cardio today.",
  "No se pudo abrir tu chequeo.": "Your check-in couldn't be opened.",
  "No se pudo abrir tu chequeo": "Your check-in couldn't be opened",
  "Volver al inicio": "Back to home",
  "tu chequeo": "your check-in",
  "Chequeo": "Check-in",
  "Tu coach pidió repetir una toma": "Your coach asked you to retake one photo",
  "Este es el mismo chequeo, no uno nuevo. Corrige lo que te señaló y vuelve a enviarlo.": "This is the same check-in, not a new one. Fix what they pointed out and send it again.",
  "Progreso del chequeo": "Check-in progress",
  "Antes de empezar, confirma cómo estás": "Before you start, confirm how you're doing",
  "Estas condiciones no son burocracia: son lo que hace que tu peso de este mes sea comparable con el del mes pasado.": "These conditions aren't red tape: they're what makes this month's weight comparable to last month's.",
  "Estás en condiciones de chequeo. Vamos por el peso.": "You're good for your check-in. On to the weight.",
  "Si algo de esto no se cumple, mejor mañana. Un chequeo hecho después de desayunar mide otra cosa; no pasa nada por posponerlo un día.": "If any of this doesn't hold, better try tomorrow. A check-in done after breakfast measures something else; there's no harm in putting it off a day.",
  "Tu peso de hoy": "Your weight today",
  "Sin ropa o con ropa ligera, con la misma báscula de siempre.": "Without clothes or in light clothing, on the same scale as always.",
  "Peso en ayunas": "Fasting weight",
  "Tu peso del mes pasado fue {peso} kg.": "Last month's weight was {peso} kg.",
  "Es tu primer pesaje: no hay con qué compararlo todavía.": "It's your first weigh-in: there's nothing to compare it to yet.",
  "Ese peso está fuera de rango": "That weight is out of range",
  "Aceptamos entre 30.0 y 250.0 kg. Revisa que no se te haya ido un dígito.": "We accept between 30.0 and 250.0 kg. Check that a digit didn't slip.",
  "Cambio de {porcentaje} %": "Change of {porcentaje} %",
  "Es un salto grande para un mes. Tu coach verá una alerta y te va a preguntar.": "That's a big jump for a month. Your coach will see an alert and ask you about it.",
  "Es más de lo habitual en un mes. Confirma el dato o vuelve a pesarte.": "It's more than usual in a month. Confirm the number or weigh yourself again.",
  "Confirmo que el dato es correcto": "I confirm the number is correct",
  "Anotado": "Noted",
  "Cambio de {porcentaje} % respecto al mes pasado. Dentro de lo esperado.": "A {porcentaje} % change from last month. Within expectations.",
  "Tus pesajes de este ciclo": "Your weigh-ins this cycle",
  "{cuantos} de {total}": "{cuantos} of {total}",
  "Puedes pesarte hasta en {n} días distintos. Se promedian para quitar el ruido de un día raro.": "You can weigh yourself on up to {n} different days. They're averaged to remove the noise of an odd day.",
  "Promedio: {promedio} kg": "Average: {promedio} kg",
  "Sale de tus {n} pesajes. Es el número que tu coach usará para ajustar tu plan.": "It comes from your {n} weigh-ins. It's the number your coach will use to adjust your plan.",
  "Con un solo pesaje usamos ese. Si te pesas otro día del ciclo, promediamos.": "With a single weigh-in we use that one. If you weigh yourself another day of the cycle, we average.",
  "¿Todo igual que el mes pasado?": "Everything the same as last month?",
  "Si cambia el lugar o la hora el dato sigue sirviendo; solo se lo anotamos a tu coach.": "If the place or time changes the number still works; we just note it for your coach.",
  "Misma báscula": "Same scale",
  "La que usaste la vez pasada": "The one you used last time",
  "Mismo lugar": "Same place",
  "Donde te pesaste la vez pasada": "Where you weighed yourself last time",
  "Misma hora": "Same time",
  "Alrededor de las {hora}": "Around {hora}",
  "A la hora de siempre": "At the usual time",
  "Cambió algo del entorno": "Something about the setting changed",
  "No bloquea tu chequeo. Se lo anotamos a tu coach para que lo tome en cuenta al comparar.": "It doesn't block your check-in. We note it for your coach to take into account when comparing.",
  "Las ocho medidas": "The eight measurements",
  "Cinta paralela al piso, apretada sin marcar la piel. Toca «¿dónde?» si dudas.": "Tape parallel to the floor, snug without pressing into the skin. Tap \"where?\" if you're unsure.",
  "Mes pasado: {valor} cm": "Last month: {valor} cm",
  "Sin referencia previa": "No previous reference",
  "¿Dónde?": "Where?",
  "Revisa estas medidas": "Review these measurements",
  "{lista}: el valor está fuera de lo que aceptamos. Casi siempre es un dígito de más o de menos.": "{lista}: the value is outside what we accept. It's almost always an extra or missing digit.",
  "de {total} capturadas": "of {total} captured",
  "de": "of",
  "capturadas": "captured",
  "de 3": "of 3",
  "Tus tres fotos": "Your three photos",
  "Del cuello para abajo. El servidor recorta la cabeza antes de guardar nada: esa parte de la imagen no llega a existir en el disco.": "From the neck down. The server crops the head before saving anything: that part of the image never exists on disk.",
  "Cómo salen bien a la primera": "How to get them right the first time",
  "Luz natural de frente, nunca a tus espaldas. Pared clara y lisa. Brazos colgando, abdomen relajado — sin meterlo. Short y top de color liso.": "Natural light from the front, never behind you. A plain, light-colored wall. Arms hanging, abdomen relaxed — not sucked in. Plain-colored shorts and top.",
  "Revisa antes de enviar": "Review before sending",
  "Después de enviarlo ya no se puede editar: tu coach lo revisa tal cual.": "Once sent, it can't be edited: your coach reviews it as-is.",
  "de {total}": "of {total}",
  "¿Algo que tu coach deba saber? (opcional)": "Anything your coach should know? (optional)",
  "Por ejemplo: dormí mal toda la semana, o me lastimé la rodilla el martes.": "For example: I slept badly all week, or I hurt my knee on Tuesday.",
  "Falta algo para poder enviarlo": "Something is missing to send it",
  "No se pudo guardar": "It couldn't be saved",
  "No se pudo guardar. Inténtalo otra vez.": "It couldn't be saved. Try again.",
  "Lo hago mañana": "I'll do it tomorrow",
  "Atrás": "Back",
  "Enviar a mi coach": "Send to my coach",
  "Continuar": "Continue",
  "No se pudo enviar. Inténtalo otra vez.": "It couldn't be sent. Try again.",
  "Dónde medir": "Where to measure",
  "Entendido": "Got it",
  "Rango aceptado: {min} a {max} cm. Si tu medida cae fuera, casi siempre es la cinta mal puesta.": "Accepted range: {min} to {max} cm. If your measurement falls outside, it's almost always the tape misaligned.",
  "Enviado": "Sent",
  "Tu chequeo ya está con tu coach": "Your check-in is already with your coach",
  "Te avisamos en cuanto lo revise. Suele tardar menos de 48 horas.": "We'll notify you as soon as they review it. It usually takes less than 48 hours.",
  "Revisar": "Review",
  "Lista": "Done",
  "Falta": "Missing",
  "No se pudo subir la foto.": "The photo couldn't be uploaded.",
  "Tu toma {rotulo}, ya recortada": "Your {rotulo} shot, already cropped",
  "Procesando…": "Processing…",
  "Recortada y guardada": "Cropped and saved",
  "Se puede mejorar": "It can be improved",
  "Repetir": "Retake",
  "Capturar": "Capture",
  "No se pudo borrar la foto.": "The photo couldn't be deleted.",
  "línea del cuello": "neck line",
  "De frente a la cámara, brazos relajados a los lados, pies a la anchura de los hombros.": "Facing the camera, arms relaxed at your sides, feet shoulder-width apart.",
  "De lado, mirando a la pared. Brazos colgando, abdomen relajado — sin meterlo.": "From the side, facing the wall. Arms hanging, abdomen relaxed — not sucked in.",
  "De espaldas, misma postura que la frontal. Hombros abajo, sin tensar.": "From the back, same pose as the front. Shoulders down, not tense.",
  "Punto más estrecho del torso, a la altura del ombligo. Cinta paralela al piso.": "Narrowest point of the torso, at navel height. Tape parallel to the floor.",
  "Zona media abdominal, relajada. Sin meter aire ni apretar.": "Mid-abdominal area, relaxed. Without sucking in air or squeezing.",
  "Punto máximo de glúteos, de pie con los pies juntos.": "Widest point of the glutes, standing with feet together.",
  "Contorno a la altura del pezón, brazos relajados a los lados.": "Circumference at nipple height, arms relaxed at your sides.",
  "Contorno axilar, por debajo de las axilas. Respiración normal.": "Circumference under the armpits. Normal breathing.",
  "Punto medio del bíceps, brazo extendido y relajado. Sin flexionar.": "Midpoint of the biceps, arm extended and relaxed. Without flexing.",
  "Punto medio entre la ingle y la rodilla, peso repartido en ambas piernas.": "Midpoint between the groin and the knee, weight on both legs.",
  "Punto máximo, planta del pie completa en el piso.": "Widest point, full foot flat on the floor.",
  "Solicitud registrada": "Request registered",
  "«{rotulo}» quedó con fecha. Tu coach tiene 20 días hábiles para contestarte.": "\"{rotulo}\" is now on the record. Your coach has 20 business days to reply.",
  "No se pudo enviar.": "It couldn't be sent.",
  "Apariencia": "Appearance",
  "De fábrica sigue a tu teléfono. Si prefieres uno fijo, elígelo aquí.": "By default it follows your phone. If you prefer a fixed one, choose it here.",
  "Datos de contacto": "Contact details",
  "Correo": "Email",
  "Para cambiarlos, escríbele a tu coach: es ella quien los tiene.": "To change them, write to your coach: she's the one who has them.",
  "Tu rutina de chequeo": "Your check-in routine",
  "Se precargan cada mes. Cámbialas solo si de verdad cambió algo.": "They're pre-filled each month. Change them only if something really changed.",
  "Báscula": "Scale",
  "Lugar de las fotos": "Photo location",
  "Hora": "Time",
  "Se toman de tu último chequeo. Si cambió algo, dilo al hacer el siguiente.": "They come from your last check-in. If something changed, say so when doing the next one.",
  "Tu historial de salud": "Your health history",
  "Dato sensible": "Sensitive data",
  "Es lo que contestaste en tu cuestionario. De esto depende que tu plan sea seguro: si cambió algo, díselo a tu coach para que lo actualice.": "It's what you answered in your questionnaire. Your plan's safety depends on it: if something changed, tell your coach to update it.",
  "Lesiones": "Injuries",
  "Lo que aceptaste": "What you accepted",
  "Sensible": "Sensitive",
  "Versión {version}": "Version {version}",
  "Pendiente": "Pending",
  "Aceptado": "Accepted",
  "Guardamos la fecha, la hora y el hash del texto exacto que aceptaste. Para revocar uno, escríbele a tu coach: revocar el protocolo fotográfico impide que genere o ajuste tu plan.": "We keep the date, time and hash of the exact text you accepted. To revoke one, write to your coach: revoking the photo protocol prevents them from generating or adjusting your plan.",
  "Tus fotos": "Your photos",
  "Se guardan cifradas y del cuello para abajo. A los 4 meses se borran, menos tu primera y tu última de cada ángulo, que se quedan para tu comparativa.": "They're stored encrypted and from the neck down. After 4 months they're deleted, except your first and last of each angle, which stay for your comparison.",
  "Descargar todo": "Download everything",
  "Solo el historial": "Only the history",
  "«Descargar todo» trae tus fotos y tu historial en un ZIP. El historial suelto es un PDF con tus medidas y tu peso.": "\"Download everything\" brings your photos and history in a ZIP. The standalone history is a PDF with your measurements and weight.",
  "Tus derechos ARCO": "Your ARCO rights",
  "Tienes respuesta en 20 días hábiles y ejecución en 15 más.": "You get a reply within 20 business days and fulfillment 15 more.",
  "Acceso": "Access",
  "Rectificación": "Rectification",
  "Cancelación": "Cancellation",
  "Oposición": "Opposition",
  "Solicitud": "Request",
  "Darme de baja": "Close my account",
  "Se borra todo: fotos, medidas e historial clínico. Descarga antes lo que quieras conservar, porque después no se puede recuperar.": "Everything is deleted: photos, measurements and clinical history. Download anything you want to keep first, because it can't be recovered afterwards.",
  "Quiero darme de baja": "I want to close my account",
  "Derecho de {codigo}": "Right to {codigo}",
  "Cuéntanos qué necesitas": "Tell us what you need",
  "Cancelar": "Cancel",
  "Enviando…": "Sending…",
  "Enviar solicitud": "Send request",
  "Detalle": "Details",
  "Explica brevemente tu solicitud": "Briefly explain your request",
  "Le llega a tu coach, que es quien responde por tus datos. Queda con fecha y tienes respuesta en 20 días hábiles.": "It reaches your coach, who is the one responsible for your data. It's time-stamped and you'll get a reply within 20 business days.",
  "Baja definitiva": "Final deactivation",
  "Esto no se puede deshacer": "This can't be undone",
  "Mejor no": "Better not",
  "Pedir mi baja": "Request my account closure",
  "Se borran tus fotos, tus medidas, tu peso y tu historial clínico. Solo se conserva el registro de movimientos, con tu identificador anonimizado, por obligación legal.": "Your photos, measurements, weight and clinical history are deleted. Only the activity log is kept, with your anonymized identifier, as a legal obligation.",
  "Si quieres conservar algo, descárgalo antes de pedirla.": "If you want to keep anything, download it before requesting it.",
  "La solicitud le llega a tu coach, que la procesa y te confirma.": "The request reaches your coach, who processes it and confirms.",
  "Esperando respuesta": "Waiting for a reply",
  "Contestada, en ejecución": "Answered, being processed",
  "Resuelta": "Resolved",
  " · antes del {fecha}": " · before {fecha}",
  "Fuera de plazo": "Past the deadline",
  "{dias} días": "{dias} days",
  "tu evolución": "your progress",
  "Con un solo chequeo todavía no hay nada que comparar. Vuelve el mes que entra.": "With only one check-in there's nothing to compare yet. Come back next month.",
  "{n} chequeos · desde {desde}": "{n} check-ins · since {desde}",
  "Tu evolución": "Your progress",
  "Tus fotos de abril se borran en 15 días": "Your April photos are deleted in 15 days",
  "Tu primera y tu última de cada ángulo se quedan. Las de en medio no.": "Your first and last of each angle stay. The ones in between don't.",
  "Antes y ahora": "Before and now",
  "Comparar": "Compare",
  "Contra": "Against",
  "Ángulo": "Angle",
  "Antes": "Before",
  "Ahora": "Now",
  "Tus números en el tiempo": "Your numbers over time",
  "{rotulo} ({unidad})": "{rotulo} ({unidad})",
  "El brazo subió mientras bajaba la cintura. Eso es recomposición: no es lo mismo que simplemente pesar menos.": "The arm went up while the waist went down. That's body recomposition: it's not the same as simply weighing less.",
  "Todos tus registros": "All your records",
  "Descargar PDF": "Download PDF",
  "Chequeo #{numero}": "Check-in #{numero}",
  "#{numero} · {fecha}": "#{numero} · {fecha}",
  "Foto purgada": "Photo purged",
  "Se borró a los 4 meses. Tus medidas y tu peso siguen aquí.": "It was deleted after 4 months. Your measurements and weight are still here.",
  "Grasa": "Fat",
  "se está borrando": "is being deleted",
  "No se pudo borrar.": "It couldn't be deleted.",
  "Fotos de tus comidas": "Photos of your meals",
  "Al corriente": "Up to date",
  "Te toca": "Your turn",
  "Tienes hasta el {fecha}.": "You have until {fecha}.",
  "Cada foto": "Each photo",
  "se borra sola a las 36 horas": "deletes itself after 36 hours",
  "de que la mandas.": "after you send it.",
  "Qué comida es": "Which meal it is",
  "Comida del martes": "Tuesday's meal",
  "Nota (opcional)": "Note (optional)",
  "Me quedé con hambre.": "I was still hungry.",
  "Subiendo…": "Uploading…",
  "Tomar o elegir foto": "Take or choose a photo",
  "No tienes fotos vigentes.": "You have no active photos.",
  "Foto de comida": "Meal photo",
  "Borrar ahora": "Delete now",
  "tu inicio": "your home",
  "Hola, {nombre}": "Hi, {nombre}",
  "Ciclo {n} · termina el {fecha}": "Cycle {n} · ends on {fecha}",
  "Tu cuenta se cierra el {fecha}": "Your account closes on {fecha}",
  "{coach} dio de baja tu cuenta. Hasta esa fecha puedes entrar y descargar lo tuyo; después se borra todo, incluidas tus fotos y tu historial.": "{coach} closed your account. Until that date you can log in and download your things; afterwards everything is deleted, including your photos and your history.",
  "Descargar mi expediente": "Download my records",
  "Tienes un aviso": "You have a notice",
  "Tienes {n} avisos": "You have {n} notices",
  "Ábrelo": "Open it",
  "Ver tus {n} avisos": "See your {n} notices",
  "Hoy te toca": "Today's agenda",
  "Tu plan": "Your plan",
  "Todavía no tienes plan": "You don't have a plan yet",
  "{n} días de entrenamiento": "{n} training days",
  "{coach} lo está armando. Te avisamos en cuanto lo publique.": "{coach} is putting it together. We'll let you know as soon as they publish it.",
  "Abrir mi plan": "Open my plan",
  "{delta} desde julio": "{delta} since July",
  "Desde que empezaste": "Since you started",
  "{signo} en {n} chequeos": "{signo} across {n} check-ins",
  "menos": "less",
  "más": "more",
  "Chequeo #{numero} · {fecha}": "Check-in #{numero} · {fecha}",
  "{coach} lo está revisando": "{coach} is reviewing it",
  "Enviaste tus ocho medidas, tu peso y las tres fotos el {fecha}. En cuanto lo valide te avisamos y se libera tu plan del ciclo siguiente.": "You sent your eight measurements, weight and three photos on {fecha}. As soon as they validate it we'll notify you and the next cycle's plan unlocks.",
  "Ver lo que enviaste": "See what you sent",
  "Empezar el del mes que entra": "Start next month's",
  "Lo último que te dijo {coach}": "The last thing {coach} told you",
  "{n} mensajes en tu hilo": "{n} messages in your thread",
  "Próximas fechas": "Upcoming dates",
  "Renovación de tu ciclo": "Your cycle renewal",
  "Pago de tu ciclo": "Your cycle payment",
  "Ciclo {numero} · {precio}": "Cycle {numero} · {precio}",
  "vencido": "overdue",
  "hoy": "today",
  "mañana": "tomorrow",
  "en {dias} días": "in {dias} days",
  "Videollamada": "Video call",
  "Presencial": "In person",
  "Llamada": "Phone call",
  " · confirmada": " · confirmed",
  "Reservar consulta": "Book a consultation",
  "Todavía no tienes ninguna agendada.": "You don't have any scheduled yet.",
  "Tus pagos": "Your payments",
  "Tienes un pago atrasado": "You have an overdue payment",
  "Lo que te toca pagar": "What you need to pay",
  "En revisión": "Under review",
  "Vencido": "Overdue",
  "Tu coach pidió otro comprobante": "Your coach asked for another receipt",
  "Tu coach lo está revisando. Te avisamos en cuanto lo confirme.": "Your coach is reviewing it. We'll let you know as soon as they confirm it.",
  "Subir comprobante": "Upload receipt",
  "No se pudo subir el comprobante.": "The receipt couldn't be uploaded.",
  "Tu coach confirma cada pago contra su estado de cuenta. Un pago vencido pausa tu plan hasta que lo valide.": "Your coach confirms each payment against their bank statement. An overdue payment pauses your plan until it's validated.",
  "Ya casi": "Almost there",
  "Falta lo último: tu primer chequeo. De ahí salen tu peso, tus medidas y el punto de partida con el que {coach} arma tu plan.": "Just the last thing: your first check-in. Your weight, measurements and the starting point from which {coach} builds your plan come from there.",
  "Qué te va a pedir": "What they'll ask of you",
  "Cómo llegas hoy: en ayunas, sin entrenar, recién despierta.": "How you show up today: fasting, untrained, freshly awake.",
  "Tu peso.": "Your weight.",
  "Tus medidas: cintura, cadera, brazo y las demás.": "Your measurements: waist, hips, arm and the rest.",
  "Tres fotos. Se guardan sin cara y se borran a los cuatro meses, menos la primera y la última.": "Three photos. They're stored without your face and deleted after four months, except the first and last.",
  "Son unos diez minutos. Puedes dejarlo a medias y seguir después.": "It takes about ten minutes. You can leave it halfway and continue later.",
  "Empezar mi chequeo": "Start my check-in",
  "Conversación": "Conversation",
  "Tus mensajes": "Your messages",
  "Aquí queda todo lo que se han dicho, en orden. Abrir el hilo marca como leídos los mensajes de tu coach.": "Everything you've said stays here, in order. Opening the thread marks your coach's messages as read.",
  "tu plan": "your plan",
  "Tu ciclo terminó": "Your cycle ended",
  "Tu plan está en pausa": "Your plan is on hold",
  "Tu plan se libera otra vez cuando empiece el ciclo nuevo. Habla con tu coach para renovarlo.": "Your plan unlocks again when the new cycle starts. Talk to your coach to renew it.",
  "Todavía no tienes un ciclo abierto. Tu coach lo activa al darte de alta.": "You don't have an open cycle yet. Your coach activates it when they sign you up.",
  "Tu comprobante todavía no ha sido validado. En cuanto tu coach lo confirme, tu plan se desbloquea solo.": "Your receipt hasn't been validated yet. As soon as your coach confirms it, your plan unlocks by itself.",
  "Ciclo {n}": "Cycle {n}",
  " · publicado el {fecha}": " · published on {fecha}",
  "Tipo de plan": "Plan type",
  "Nutrición": "Nutrition",
  "Entrenamiento": "Training",
  "Tu coach todavía no publica este plan. Te avisamos en cuanto esté.": "Your coach hasn't published this plan yet. We'll let you know as soon as it's ready.",
  "Tu objetivo del día": "Your daily goal",
  "Proteína": "Protein",
  "Carbohidratos": "Carbs",
  "Notas de tu coach": "Notes from your coach",
  "Tus restricciones": "Your restrictions",
  "Salen de tu cuestionario; si cambian, actualízalas en tu cuenta.": "They come from your questionnaire; if they change, update them in your account.",
  "Descargar mi plan en PDF": "Download my plan as a PDF",
  "Para imprimirlo o llevarlo al súper sin depender de la señal.": "To print it or take it to the grocery store without relying on a signal.",
  "No se pudo generar el documento.": "The document couldn't be generated.",
  "Generando…": "Generating…",
  "Plantilla base": "Base template",
  "{n} días por semana": "{n} days per week",
  "Hoy": "Today",
  "Notas de ejecución": "Execution notes",
  "Ojo con esto": "Watch out for this",
  "Si duele, para.": "If it hurts, stop.",
  "Descargar mi rutina en PDF": "Download my routine as a PDF",
  "Trae una columna en blanco para anotar tus cargas a mano en el gimnasio.": "It has a blank column to write down your loads by hand at the gym.",
  "Por video": "By video",
  "Por teléfono": "By phone",
  "En persona": "In person",
  "{rotulo} · termina a las {hora}": "{rotulo} · ends at {hora}",
  "termina a las {hora}": "ends at {hora}",
  "No se pudo reservar.": "It couldn't be booked.",
  "los horarios libres": "the available slots",
  "Con tu coach": "With your coach",
  "Reserva tu consulta": "Book your consultation",
  "Elige la hora que te acomode. Queda agendada al momento.": "Choose a time that suits you. It's booked on the spot.",
  "Ahora mismo no hay horarios libres. Tu coach abre más conforme se acerquen las fechas.": "There are no available slots right now. Your coach opens more as dates get closer.",
  "Confirma tu consulta": "Confirm your consultation",
  "Reservar": "Book",
  "Termina a las {hora}. Las horas están en tu zona horaria.": "It ends at {hora}. Times are in your time zone.",
  "Cómo prefieres la consulta": "How you prefer the consultation",
  "Si te surge algo, escríbele a tu coach para moverla.": "If something comes up, write to your coach to move it.",
  "Tu consulta quedó agendada": "Your consultation is booked",
  "Ir a mi inicio": "Go to my home",
  "Te llega el recordatorio un día antes": "You'll get the reminder the day before",
  "Conoce a tu coach y contesta": "Meet your coach and answer",
  "Lesiones, condiciones y el plan que quieres. De ahí sale tu primer plan.": "Injuries, conditions and the plan you want. Your first plan comes out of that.",
  "Reserva tu primera consulta": "Book your first consultation",
  "Eliges la hora que te acomode de las que tu coach tiene abiertas.": "You choose a time that suits you from the ones your coach has open.",
  "Sube tu comprobante de inscripción": "Upload your enrollment receipt",
  "Se paga una sola vez, al entrar.": "It's paid once, on sign-up.",
  "tu registro": "your registration",
  "Ya está todo de tu lado": "Everything on your side is done",
  "Te falta poco": "Almost there",
  "Tu coach revisa tu solicitud y confirma tu consulta. Te avisamos por correo en cuanto lo haga.": "Your coach reviews your request and confirms your consultation. We'll email you as soon as they do.",
  "Termina estos pasos y tu coach recibe tu solicitud.": "Finish these steps and your coach receives your request.",
  "Lo que capturaste se guarda {tiempo} más. Si no terminas, se borra solo: es tu dato y no lo guardamos de más.": "What you've entered is kept for {tiempo} longer. If you don't finish, it deletes itself: it's your data and we don't keep it longer than needed.",
  "un día": "one day",
  "{n} días": "{n} days",
  "listo": "done",
  "Entras con tu correo y la contraseña que elegiste.": "You log in with the email and password you chose.",
  "Ver horarios": "See available times",
  "Qué sigue": "What's next",
  "Tu coach revisa lo que capturaste, confirma tu consulta y valida tu pago. Cuando te acepte se abre tu primer chequeo, y ahí empieza el método: peso, medidas y fotos.": "Your coach reviews what you entered, confirms your consultation and validates your payment. When they accept you, your first check-in opens, and that's where the method begins: weight, measurements and photos.",
  "Mientras tanto no hace falta que hagas nada.": "Meanwhile you don't need to do anything.",
  "Datos de salud": "Health data",
  "Cintura": "Waist",
  "Abdomen": "Abdomen",
  "Cadera": "Hips",
  "Busto": "Bust",
  "Pecho": "Chest",
  "Brazo": "Arm",
  "Muslo": "Thigh",
  "Pantorrilla": "Calf",
  "Pérdida de grasa": "Fat loss",
  "Ganancia de masa": "Muscle gain",
  "Recomposición": "Body recomposition",
  "Frontal": "Front",
  "Perfil": "Profile",
  "Espalda": "Back",
  "Muy poco activa": "Very little active",
  "Poco activa": "Little active",
  "Activa": "Active",
  "Muy activa": "Very active",
  "Intensa": "Intense",
  "Muy intensa": "Very intense",
  "Atleta": "Athlete",
  "Atleta de élite": "Elite athlete",
  "Tu cuenta": "Your account",
  "Privacidad": "Privacy",
  "Mi plan": "My plan",
  "Volver a inicio": "Back to home",
  "Borrador": "Draft",
  "Validado": "Validated",
  "Rechazado": "Rejected",
  "Descartado": "Discarded",
  "confirmada": "confirmed",
  "el valor está fuera de lo que aceptamos. Casi siempre es un dígito de más o de menos.":
    "the value is outside what we accept. It's usually a digit too many or too few.",
};